"""Unified error codes and categories for the entire Agent Runtime."""

from __future__ import annotations

from enum import StrEnum


class ErrorCategory(StrEnum):
    TRANSIENT_PROVIDER = "transient_provider"
    PERMANENT_PROVIDER = "permanent_provider"
    INVALID_JSON = "invalid_json"
    SCHEMA_MISMATCH = "schema_mismatch"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"
    SECURITY_VIOLATION = "security_violation"
    BUDGET_EXCEEDED = "budget_exceeded"
    TOOL_LIMIT_EXCEEDED = "tool_limit_exceeded"
    TIMEOUT = "timeout"
    CANCELLED = "cancelled"
    INTERNAL_ERROR = "internal_error"


class ErrorCode(StrEnum):
    # Provider errors
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_SERVER_ERROR = "PROVIDER_SERVER_ERROR"
    PROVIDER_CONNECTION_ERROR = "PROVIDER_CONNECTION_ERROR"
    PROVIDER_AUTH_FAILURE = "PROVIDER_AUTH_FAILURE"
    PROVIDER_MODEL_NOT_FOUND = "PROVIDER_MODEL_NOT_FOUND"

    # JSON errors
    JSON_PARSE_FAILED = "JSON_PARSE_FAILED"
    JSON_NOT_OBJECT = "JSON_NOT_OBJECT"

    # Schema errors
    SCHEMA_MISSING_FIELD = "SCHEMA_MISSING_FIELD"
    SCHEMA_WRONG_TYPE = "SCHEMA_WRONG_TYPE"
    SCHEMA_EXTRA_FIELD = "SCHEMA_EXTRA_FIELD"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"

    # Evidence errors
    EVIDENCE_NOT_FOUND = "EVIDENCE_NOT_FOUND"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    EVIDENCE_FILE_LIMIT = "EVIDENCE_FILE_LIMIT"

    # Security errors
    SECURITY_PATH_TRAVERSAL = "SECURITY_PATH_TRAVERSAL"
    SECURITY_SENSITIVE_FILE = "SECURITY_SENSITIVE_FILE"
    SECURITY_PROMPT_INJECTION = "SECURITY_PROMPT_INJECTION"
    SECURITY_REDACTION_FAILED = "SECURITY_REDACTION_FAILED"

    # Budget errors
    BUDGET_TOTAL_TOKENS = "BUDGET_TOTAL_TOKENS"
    BUDGET_AGENT_TOKENS = "BUDGET_AGENT_TOKENS"
    BUDGET_LLM_CALLS = "BUDGET_LLM_CALLS"
    BUDGET_WALL_TIME = "BUDGET_WALL_TIME"
    BUDGET_RETRY_EXHAUSTED = "BUDGET_RETRY_EXHAUSTED"
    BUDGET_REVISION_EXHAUSTED = "BUDGET_REVISION_EXHAUSTED"

    # Tool errors
    TOOL_NOT_REGISTERED = "TOOL_NOT_REGISTERED"
    TOOL_PARAM_INVALID = "TOOL_PARAM_INVALID"
    TOOL_PATH_DENIED = "TOOL_PATH_DENIED"

    # Timeout
    AGENT_TIMEOUT = "AGENT_TIMEOUT"
    STAGE_TIMEOUT = "STAGE_TIMEOUT"

    # Cancellation
    RUN_CANCELLED = "RUN_CANCELLED"

    # Internal
    INTERNAL_UNEXPECTED = "INTERNAL_UNEXPECTED"
    CHECKPOINT_CORRUPT = "CHECKPOINT_CORRUPT"
    ARTIFACT_WRITE_FAILED = "ARTIFACT_WRITE_FAILED"


# Mapping from ErrorCode to ErrorCategory
_ERROR_CODE_CATEGORY: dict[ErrorCode, ErrorCategory] = {
    ErrorCode.PROVIDER_TIMEOUT: ErrorCategory.TRANSIENT_PROVIDER,
    ErrorCode.PROVIDER_RATE_LIMITED: ErrorCategory.TRANSIENT_PROVIDER,
    ErrorCode.PROVIDER_SERVER_ERROR: ErrorCategory.TRANSIENT_PROVIDER,
    ErrorCode.PROVIDER_CONNECTION_ERROR: ErrorCategory.TRANSIENT_PROVIDER,
    ErrorCode.PROVIDER_AUTH_FAILURE: ErrorCategory.PERMANENT_PROVIDER,
    ErrorCode.PROVIDER_MODEL_NOT_FOUND: ErrorCategory.PERMANENT_PROVIDER,
    ErrorCode.JSON_PARSE_FAILED: ErrorCategory.INVALID_JSON,
    ErrorCode.JSON_NOT_OBJECT: ErrorCategory.INVALID_JSON,
    ErrorCode.SCHEMA_MISSING_FIELD: ErrorCategory.SCHEMA_MISMATCH,
    ErrorCode.SCHEMA_WRONG_TYPE: ErrorCategory.SCHEMA_MISMATCH,
    ErrorCode.SCHEMA_EXTRA_FIELD: ErrorCategory.SCHEMA_MISMATCH,
    ErrorCode.SCHEMA_VALIDATION_FAILED: ErrorCategory.SCHEMA_MISMATCH,
    ErrorCode.EVIDENCE_NOT_FOUND: ErrorCategory.INSUFFICIENT_EVIDENCE,
    ErrorCode.EVIDENCE_INSUFFICIENT: ErrorCategory.INSUFFICIENT_EVIDENCE,
    ErrorCode.EVIDENCE_FILE_LIMIT: ErrorCategory.INSUFFICIENT_EVIDENCE,
    ErrorCode.SECURITY_PATH_TRAVERSAL: ErrorCategory.SECURITY_VIOLATION,
    ErrorCode.SECURITY_SENSITIVE_FILE: ErrorCategory.SECURITY_VIOLATION,
    ErrorCode.SECURITY_PROMPT_INJECTION: ErrorCategory.SECURITY_VIOLATION,
    ErrorCode.SECURITY_REDACTION_FAILED: ErrorCategory.SECURITY_VIOLATION,
    ErrorCode.BUDGET_TOTAL_TOKENS: ErrorCategory.BUDGET_EXCEEDED,
    ErrorCode.BUDGET_AGENT_TOKENS: ErrorCategory.BUDGET_EXCEEDED,
    ErrorCode.BUDGET_LLM_CALLS: ErrorCategory.BUDGET_EXCEEDED,
    ErrorCode.BUDGET_WALL_TIME: ErrorCategory.BUDGET_EXCEEDED,
    ErrorCode.BUDGET_RETRY_EXHAUSTED: ErrorCategory.BUDGET_EXCEEDED,
    ErrorCode.BUDGET_REVISION_EXHAUSTED: ErrorCategory.BUDGET_EXCEEDED,
    ErrorCode.TOOL_NOT_REGISTERED: ErrorCategory.TOOL_LIMIT_EXCEEDED,
    ErrorCode.TOOL_PARAM_INVALID: ErrorCategory.TOOL_LIMIT_EXCEEDED,
    ErrorCode.TOOL_PATH_DENIED: ErrorCategory.SECURITY_VIOLATION,
    ErrorCode.AGENT_TIMEOUT: ErrorCategory.TIMEOUT,
    ErrorCode.STAGE_TIMEOUT: ErrorCategory.TIMEOUT,
    ErrorCode.RUN_CANCELLED: ErrorCategory.CANCELLED,
    ErrorCode.INTERNAL_UNEXPECTED: ErrorCategory.INTERNAL_ERROR,
    ErrorCode.CHECKPOINT_CORRUPT: ErrorCategory.INTERNAL_ERROR,
    ErrorCode.ARTIFACT_WRITE_FAILED: ErrorCategory.INTERNAL_ERROR,
}


def error_category(code: ErrorCode) -> ErrorCategory:
    """Return the category for a given error code."""
    return _ERROR_CODE_CATEGORY[code]


def is_retryable(code: ErrorCode) -> bool:
    """True if errors of this code should be retried."""
    return error_category(code) in {
        ErrorCategory.TRANSIENT_PROVIDER,
        ErrorCategory.TIMEOUT,
    }
